# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'sms', '0001_initial'), (b'sms', '0002_auto_20180618_0946'), (b'sms', '0003_auto_20180625_0722'), (b'sms', '0004_auto_20180625_0942'), (b'sms', '0005_customersms_retry_count'), (b'sms', '0006_customersms_status_detail'), (b'sms', '0007_remove_customersms_retry_count')]

    initial = True

    dependencies = [
        ('wifiportal', '0020_auto_20180615_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wifiportal.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=160, verbose_name='SMS Message')),
                ('scheduled_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Send SMS on')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wifiportal.Organization')),
                ('recipient', models.ManyToManyField(through='sms.CustomerSMS', to=b'wifiportal.Customer')),
            ],
            options={
                'verbose_name_plural': 'SMS',
                'permissions': (('alter_all_SMS', 'Can alter all SMS'),),
            },
        ),
        migrations.AddField(
            model_name='customersms',
            name='sms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.SMS'),
        ),
        migrations.AlterModelOptions(
            name='customersms',
            options={'permissions': (('alter_all_CustomerSMS', 'Can alter all Customer SMS'),), 'verbose_name_plural': 'CustomerSMS'},
        ),
        migrations.AddField(
            model_name='customersms',
            name='sms_gateway',
            field=models.CharField(choices=[(b'SPARROW_SMS', b'SPARROW_SMS')], default='SPARROW_SMS', max_length=50, verbose_name=b'SMS Gateway'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersms',
            name='status',
            field=models.CharField(choices=[(b'PENDING', b'PENDING'), (b'SUCCESS', b'SUCCESS'), (b'FAILED', b'FAILED')], default=b'PENDING', max_length=50, verbose_name=b'SMS Status'),
        ),
        migrations.AddField(
            model_name='customersms',
            name='status_detail',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name=b'SMS Status detail'),
        ),
    ]
