# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 08:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid mac address', regex='(?:(?:[0-9a-fA-F]){2}:){5}(?:[0-9a-fA-F]){2}')], verbose_name='Router Mac Address')),
                ('nasid', models.CharField(max_length=1000, verbose_name='Router Name')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_time', models.TimeField(verbose_name='Router Time')),
                ('uptime', models.TimeField(verbose_name='Router Uptime')),
                ('load_average', models.FloatField(verbose_name='Average Router Load %')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mikrotiklog.Router', verbose_name='Router')),
            ],
        ),
    ]
