# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotiklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='uptime',
            field=models.DurationField(verbose_name='Router Uptime'),
        ),
    ]
