# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotiklog', '0002_auto_20180204_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Customer Entry Time'),
        ),
    ]
