# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotiklog', '0004_auto_20180605_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Customer Entry Time'),
        ),
    ]
