# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotiklog', '0005_auto_20180608_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status Log Entry Time'),
        ),
    ]
