# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('description', models.CharField(max_length=500, verbose_name='Item Desctiption')),
                ('image', models.ImageField(upload_to=b'', verbose_name='Item Photo')),
                ('featured', models.BooleanField(verbose_name='Featured Item')),
            ],
            options={
                'permissions': (('alter_all_menu_items', 'Can alter all menu items'),),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Restaurant name')),
                ('location', models.CharField(max_length=100, verbose_name='Restaurant Location')),
                ('cover_image', models.ImageField(upload_to=b'', verbose_name='Restaurant Cover Pics')),
                ('logo', models.ImageField(upload_to=b'', verbose_name='Restaurant Logo')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wifiportal.Restaurant'),
        ),
    ]
