# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Customer Phone Number')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Customer Date of Birth')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wifiportal.Restaurant')),
            ],
            options={
                'permissions': (('alter_all_customer_data', 'Can alter all customer data'),),
            },
        ),
    ]
