# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 05:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0003_auto_20180107_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='entry_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Customer Entry Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number!!! Please enter valid 10 digit phone number', regex='^9\\d{9}$')], verbose_name='Customer Phone Number'),
        ),
    ]
