# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 07:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0006_auto_20180111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number!!! Please enter valid 10 digit phone number', regex='^9\\d{9}$')], verbose_name='Customer Phone Number'),
        ),
    ]
