# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0011_auto_20180119_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_password', models.BooleanField(default=False, verbose_name='Enable Password on hotspot page')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Password for hotspot')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wifiportal.Organization')),
            ],
            options={
                'permissions': (('alter_all_hotspot_config', 'Can alter all hotspot configs'),),
            },
        ),
    ]
