# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0012_hotspotconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Customer Entry Time'),
        ),
    ]
