# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0013_auto_20180127_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotconfig',
            name='login_redirect_page',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Redirect to this page after hotspot login'),
        ),
    ]
