# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0014_hotspotconfig_login_redirect_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotconfig',
            name='password_changed_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password Changed on'),
        ),
    ]
