# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0015_hotspotconfig_password_changed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Customer Entry Time'),
        ),
    ]
