# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 09:26
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0016_customer_last_login_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'', verbose_name='Item Photo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'', verbose_name='Organization Logo'),
        ),
    ]
