# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0017_auto_20180228_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspotconfig',
            options={'permissions': (('alter_all_hotspot_config', 'Can alter all hotspot configs'), ('manage_hotspot_password', 'Can manage own hotspot password'))},
        ),
    ]
