# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 09:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0018_auto_20180319_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kathmandu', 'Asia/Kathmandu'), ('Asia/Dubai', 'Asia/Dubai')], default='Asia/Kathmandu', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number!!! Please enter valid 10 digit phone number', regex='^(?:05|9\\d)\\d{8}$')], verbose_name='Customer Phone Number'),
        ),
    ]
