# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0019_auto_20180528_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspotconfig',
            options={'permissions': (('alter_all_hotspot_config', 'Can alter all hotspot configs'), ('manage_hotspot_password', 'Can manage own hotspot password'), ('can_add_advertisement_image', 'Can add advertisement image'))},
        ),
        migrations.AddField(
            model_name='hotspotconfig',
            name='advertisement_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'', verbose_name='Advertisement Image'),
        ),
        migrations.AddField(
            model_name='hotspotconfig',
            name='enable_advertisement_image',
            field=models.BooleanField(default=False),
        ),
    ]
