# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiportal', '0021_auto_20180713_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Block this person'),
        ),
    ]
